[test]
preload = ["./happydom.ts", "./tests/setup.ts"] # happydom.ts のパスを修正
coverage = true
# environment = "happy-dom" # setup.tsで設定するためコメントアウト

# テストディレクトリとパターンの設定
testDirectory = "./src"
testPattern = "**/*.test.{ts,tsx}"

# カバレッジ設定
coveragePattern = [
  "src/**/*.{ts,tsx}",
  "!src/**/*.d.ts",
  "!src/**/*.test.{ts,tsx}",
  "!tests/**/*",
  "!**/node_modules/**"
]

# テスト環境変数
[env]
NODE_ENV = "test"

# テストスイートの設定
# [test.setup] # usesHappyDOMはenvironmentで設定するため削除
# usesHappyDOM = true