# Cloud Run サービス定義
# Cloud Run のマニフェストはserving.knative.dev/v1スキーマを使用します
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: suzumina-click-nextjs-app
  # アノテーションでCloud Runの追加設定を指定できます
  annotations:
    # ブラウザから直接アクセスできるように認証を無効化
    run.googleapis.com/ingress: all
spec:
  template:
    spec:
      containers:
        - image: suzumina-click-nextjs
          # コンテナポートを指定
          ports:
            - containerPort: 3000
          # リソース制限
          resources:
            limits:
              memory: 1Gi
              cpu: 1
          # 環境変数
          env:
            - name: NODE_ENV
              value: production