apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: suzumina-web
  annotations:
    # Cloud Run specific annotations
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
    # CPU allocation
    run.googleapis.com/cpu-throttling: "false"
spec:
  template:
    metadata:
      annotations:
        # Scaling settings
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
        # Resource limits
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        # Startup probe settings
        run.googleapis.com/startup-cpu-boost: "true"
        # Cloud SQL connections (if needed)
        # run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:INSTANCE_NAME
    spec:
      # Container timeout
      timeoutSeconds: 300
      # Service account (adjust as needed)
      serviceAccountName: suzumina-web-sa
      containers:
      - name: suzumina-web
        # Image will be set during deployment
        image: gcr.io/PROJECT_ID/suzumina-web:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        # Environment variables for production
        - name: NODE_ENV
          value: "production"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: PORT
          value: "8080"
        - name: HOSTNAME
          value: "0.0.0.0"
        # Google Cloud specific environment variables
        - name: GOOGLE_CLOUD_PROJECT
          value: "YOUR_PROJECT_ID"  # デプロイ時に実際のプロジェクトIDに置換
        # Add other environment variables as needed
        # - name: YOUTUBE_API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: youtube-api-key
        #       key: key
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      # Scale to zero settings
      containerConcurrency: 1000