# .github/dependabot.yml
version: 2
updates:
  # GitHub Actions のバージョンを維持
  - package-ecosystem: "github-actions"
    directory: "/" # ルートディレクトリのワークフローをチェック
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # bun (npm) の依存関係を維持 (ルート)
  - package-ecosystem: "npm" # bun は npm レジストリを使用
    directory: "/" # ルートの package.json をチェック
    schedule:
      interval: "weekly"
    versioning-strategy: "increase" # マイナー・パッチ更新のみ
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # bun (npm) の依存関係を維持 (apps/web)
  - package-ecosystem: "npm"
    directory: "/apps/web" # apps/web の package.json をチェック
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)" # devDependencies 用のプレフィックス
      include: "scope"