version = 1

test_patterns = [
  "**/*.test.*",
  "**/tests/**",
]

exclude_patterns = [
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/.next/**",
  ".coverage/**",
  "**/.turbo/**",
  "**/.vercel/**",
  "iac/**",
  "*.tfstate",
  "*.tfstate.*",
  "*.tfvars",
  "**/.terraform/**",
  "*.pem",
  ".DS_Store",
  ".env",
  ".env.*",
  "*.log",
  ".pnp.js",
  ".pnp.loader.mjs",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs", "browser"]

# Test Coverage Analyzer
[[analyzers]]
name = "test-coverage"
enabled = true

  [analyzers.meta]
  coverage_file = "apps/web/coverage/lcov.info"
  format = "lcov"

# Secrets Analyzer
[[analyzers]]
name = "secrets"
enabled = true
