version = 1

test_patterns = [
  "**/*.test.*",
  "**/tests/**",
]

exclude_patterns = [
  "docs/**",
  "README.md",
  "**/node_modules/**",
  "**/dist/**",
  "**/build/**",
  "**/.next/**",
  "**/.turbo/**",
  "**/.vercel/**",
  "*.tfstate",
  "*.tfstate.*",
  "*.tfvars",
  "**/.terraform/**",
  "*.pem",
  ".DS_Store",
  ".env",
  ".env.*",
  "*.log",
  ".pnp.js",
  ".pnp.loader.mjs",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = ["nodejs", "browser"]

# Secrets Analyzer
[[analyzers]]
name = "secrets"
enabled = true

# Terraform Analyzer
[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true
