apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: suzumina-click

# manifests セクションで Cloud Run のマニフェストを定義します
manifests:
  # Cloud Run サービス定義を含むYAMLファイルを指定
  rawYaml:
    - apps/web/cloud-run-service.yaml

build:
  artifacts:
    - image: suzumina-click-nextjs
      context: .
      docker:
        dockerfile: apps/web/Dockerfile
  # ローカルビルド時にCloudRunにデプロイするためには明示的にpush:trueが必要
  local:
    push: true
  # 複数プラットフォーム対応（Cloud Runの要件）
  platforms:
    - linux/amd64

deploy:
  # Cloud Run デプロイヤーの設定
  # ドキュメントによると、artifacts フィールドではなく projectid と region のみ設定します
  cloudrun:
    projectid: suzumina-click-firebase
    region: asia-northeast1

profiles:
  - name: dev
    build:
      tagPolicy:
        gitCommit: {}
    # プロファイル内でもCloud Runの設定に合わせて修正
    deploy:
      cloudrun:
        projectid: suzumina-click-firebase
        region: asia-northeast1

  - name: staging
    build:
      tagPolicy:
        gitCommit: {}
    # プロファイル内でもCloud Runの設定に合わせて修正
    deploy:
      cloudrun:
        projectid: suzumina-click-firebase
        region: asia-northeast1

# ポートフォワーディング設定
portForward:
  - resourceType: service
    resourceName: suzumina-click-nextjs-app
    localPort: 9001