name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# バージョン情報はpackage.jsonから読み取ります
# パッケージからバージョンを動的に取得するステップが最初のジョブにあります

jobs:
  # リポジトリ全体の共通検証
  common-lint:
    name: 共通コード検証
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.read_engines.outputs.node_version }}
      pnpm_version: ${{ steps.read_engines.outputs.pnpm_version }}

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
      
      # package.jsonからenginesのバージョンを読み取る
      - name: パッケージからエンジンバージョンを読み取る
        id: read_engines
        run: |
          # package.jsonからNode.jsとpnpmのバージョンを取得
          NODE_VERSION=$(node -p "require('./package.json').engines.node")
          PNPM_VERSION=$(node -p "require('./package.json').engines.pnpm")
          
          echo "取得したバージョン情報: Node.js=$NODE_VERSION, pnpm=$PNPM_VERSION"
          
          # GitHub Actionsの出力として設定
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "pnpm_version=$PNPM_VERSION" >> $GITHUB_OUTPUT

      # 複合アクションを使用してNode.js環境をセットアップ
      - name: Node.js環境のセットアップ
        uses: ./.github/actions/setup-node-env
        with:
          node-version: ${{ steps.read_engines.outputs.node_version }}
          pnpm-version: ${{ steps.read_engines.outputs.pnpm_version }}

      - name: Biome によるコード検証
        run: pnpm lint

  # Next.jsウェブアプリ（Web）の検証
  web-checks:
    uses: ./.github/workflows/reusable/build-and-test-app.yml
    needs: common-lint
    with:
      app-name: 'web'
      package-name: '@suzumina.click/web'
      run-tests: true
      run-build: true
      node-version: ${{ needs.common-lint.outputs.node_version }}
      pnpm-version: ${{ needs.common-lint.outputs.pnpm_version }}

  # Cloud Functions の検証
  functions-checks:
    uses: ./.github/workflows/reusable/build-and-test-app.yml
    needs: common-lint
    with:
      app-name: 'functions'
      package-name: '@suzumina.click/functions'
      run-tests: true
      run-build: true
      node-version: ${{ needs.common-lint.outputs.node_version }}
      pnpm-version: ${{ needs.common-lint.outputs.pnpm_version }}

  # すべての検証が完了したら通知
  notify-success:
    name: 検証完了通知
    runs-on: ubuntu-latest
    needs: [web-checks, functions-checks]
    if: ${{ success() }}

    steps:
      - name: 検証完了メッセージ
        run: echo "::notice title=CI検証成功::すべてのテストとビルド検証が成功しました！"