name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 共通の環境変数
env:
  NODE_VERSION: '22'
  PNPM_VERSION: '10'

jobs:
  # リポジトリ全体の共通検証
  common-lint:
    name: 共通コード検証
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: pnpm のインストール
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: 依存関係のキャッシュ
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 依存関係のインストール
        run: pnpm install

      - name: Biome によるコード検証
        run: pnpm lint

  # Next.jsウェブアプリ（Web）の検証
  web-checks:
    name: Webアプリケーション検証
    runs-on: ubuntu-latest
    needs: common-lint

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: pnpm のインストール
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: 依存関係のキャッシュ
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-web-${{ hashFiles('apps/web/pnpm-lock.yaml', 'pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-web-

      - name: 依存関係のインストール
        run: pnpm install

      - name: Webアプリのテスト
        run: pnpm --filter @suzumina.click/web test

      - name: Webアプリのビルド
        run: pnpm --filter @suzumina.click/web build

      # ビルドサイズの分析（オプション）
      - name: ビルドサイズの分析
        run: |
          echo "Webアプリのビルドサイズ分析:"
          du -sh apps/web/.next/

  # Cloud Functions の検証
  functions-checks:
    name: Cloud Functions検証
    runs-on: ubuntu-latest
    needs: common-lint

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js のセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: pnpm のインストール
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: false

      - name: 依存関係のキャッシュ
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            **/node_modules
          key: ${{ runner.os }}-pnpm-functions-${{ hashFiles('apps/functions/pnpm-lock.yaml', 'pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-functions-

      - name: 依存関係のインストール
        run: pnpm install

      - name: Cloud Functionsのテスト
        run: pnpm --filter @suzumina.click/functions test

      - name: Cloud Functionsのビルド
        run: pnpm --filter @suzumina.click/functions build

  # すべての検証が完了したら通知
  notify-success:
    name: 検証完了通知
    runs-on: ubuntu-latest
    needs: [web-checks, functions-checks]
    if: ${{ success() }}

    steps:
      - name: 検証完了メッセージ
        run: echo "::notice title=CI検証成功::すべてのテストとビルド検証が成功しました！"