name: CI

on:
  workflow_call: {}  # 再利用可能なワークフローとして定義
  pull_request:     # PRのみをトリガーとする
    types: [opened, synchronize]

jobs:
  check:
    name: Check
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Spell Check
        run: bun run spell-check

      - name: Run CI Checks (Lint, Format, Type Check)
        run: bun run ci:check

      - name: Run Tests and Generate Coverage
        run: bun run test:coverage

      - name: Debug DSN existence # このステップを追加
        run: |
          if [ -z "$DEEPSOURCE_DSN" ]; then
            echo "DEEPSOURCE_DSN is not set or empty"
          else
            echo "DEEPSOURCE_DSN is set (length: ${#DEEPSOURCE_DSN})"
            # DSN自体は機密情報なので、値そのものは出力しないように注意
          fi
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}

      - name: Report Test Coverage to DeepSource # 元々のステップ
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key javascript --value-file ./apps/web/coverage/lcov.info
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
