name: Claude PR Review API

on:
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write

jobs:
  claude-review:
    if: |
      github.event.issue.pull_request && 
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
      - name: Post Acknowledgment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '🤖 Claude is analyzing your request...'
            });

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github/actions/claude-review
          sparse-checkout-cone-mode: false

      - name: Run Claude Review
        id: claude-review
        uses: ./.github/actions/claude-review
        with:
          anthropic-api-key: ${{ secrets.ANTHROPIC_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.issue.number }}
          comment: ${{ github.event.comment.body }}
          comment-author: ${{ github.event.comment.user.login }}

      - name: Post Review Result
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const isError = '${{ steps.claude-review.outputs.error }}' === 'true';
            const message = `${{ steps.claude-review.outputs.message }}`;
            
            let body = '';
            
            if (isError) {
              body = `## ⚠️ Claude Review Error\n\n${message}\n\n`;
              body += `### Troubleshooting\n`;
              body += `- Ensure \`ANTHROPIC_API_KEY\` is set in repository secrets\n`;
              body += `- Check if the API key has available credits\n`;
              body += `- Verify the API key permissions\n`;
            } else {
              body = `## 🤖 Claude Code Review\n\n${message}\n\n`;
              body += `---\n`;
              body += `*Review requested by @${{ github.event.comment.user.login }}*`;
            }
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });