name: '本番環境デプロイ'

on:
  # 手動トリガー
  workflow_dispatch:
    inputs:
      branch:
        description: 'デプロイするブランチ'
        required: true
        default: 'main'
        type: string
  
  # mainブランチへのマージ後、CI成功時に自動実行
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  
  # 特定パスの変更の場合も自動でデプロイ（ファイル単位の変更検知）
  push:
    branches:
      - main
    paths:
      # Web アプリケーション変更時
      - 'apps/web/**'
      # Cloud Functions 変更時
      - 'apps/functions/**'

# Workload Identity Federationに必要な権限設定
permissions:
  contents: read
  id-token: write  # Google Cloud認証に必要

# リージョン設定のみ残し、Node.jsとpnpmのバージョンはpackage.jsonから読み取る
env:
  REGION: 'asia-northeast1'

jobs:
  # デプロイ条件の確認とバージョン情報の読み取り
  verify-deployment-conditions:
    name: 'デプロイ条件の確認'
    runs-on: ubuntu-latest
    # CIワークフローが成功した場合または手動トリガーの場合、またはパス変更時に実行
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'push'
    
    outputs:
      deploy_branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || 'main' }}
      node_version: ${{ steps.read_engines.outputs.node_version }}
      pnpm_version: ${{ steps.read_engines.outputs.pnpm_version }}
      web_changed: ${{ steps.filter.outputs.web || 'false' }}
      functions_changed: ${{ steps.filter.outputs.functions || 'false' }}

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'push' && 2 || 1 }}  # push時は差分検出のため2に設定
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || 'main' }}

      # push時のみパス変更を検出
      - name: パス変更検出
        if: github.event_name == 'push'
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            web:
              - 'apps/web/**'
            functions:
              - 'apps/functions/**'
      
      # 手動トリガーやCI成功後のデプロイ時はすべての対象をデプロイ
      - name: 手動/CI成功後の場合は全デプロイを設定
        if: github.event_name != 'push'
        run: |
          echo "web=true" >> $GITHUB_OUTPUT
          echo "functions=true" >> $GITHUB_OUTPUT
        id: non_push_filter

      # package.jsonからenginesのバージョンを読み取る
      - name: パッケージからエンジンバージョンを読み取る
        id: read_engines
        run: |
          # package.jsonからNode.jsとpnpmのバージョンを取得
          NODE_VERSION=$(node -p "require('./package.json').engines.node")
          PNPM_VERSION=$(node -p "require('./package.json').engines.pnpm")
          
          echo "取得したバージョン情報: Node.js=$NODE_VERSION, pnpm=$PNPM_VERSION"
          
          # GitHub Actionsの出力として設定
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "pnpm_version=$PNPM_VERSION" >> $GITHUB_OUTPUT
      
      - name: デプロイ情報を出力
        run: |
          echo "デプロイ情報:"
          echo "- トリガー: ${{ github.event_name }}"
          echo "- ブランチ: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || 'main' }}"
          echo "- Webアプリ変更: ${{ steps.filter.outputs.web == 'true' || steps.non_push_filter.outputs.web == 'true' && '変更あり' || '変更なし' }}"
          echo "- Functions変更: ${{ steps.filter.outputs.functions == 'true' || steps.non_push_filter.outputs.functions == 'true' && '変更あり' || '変更なし' }}"
          echo "- Node.js: ${{ steps.read_engines.outputs.node_version }}"
          echo "- pnpm: ${{ steps.read_engines.outputs.pnpm_version }}"
          echo "- コミット: ${{ github.sha }}"
          echo "- 実行者: ${{ github.actor }}"
          echo "- 日時: $(date '+%Y年%m月%d日 %H:%M:%S')"

  # Next.jsウェブアプリケーションのデプロイ
  deploy-web-app:
    name: 'Webアプリケーションデプロイ'
    needs: verify-deployment-conditions
    # 変更検知で変更がある場合、または手動・CI経由の場合に実行
    if: |
      needs.verify-deployment-conditions.outputs.web_changed == 'true' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.verify-deployment-conditions.outputs.deploy_branch }}
      
      # 複合アクションを使用してNode.js環境をセットアップ
      - name: Node.js環境のセットアップ
        uses: ./.github/actions/setup-node-env
        with:
          node-version: ${{ needs.verify-deployment-conditions.outputs.node_version }}
          pnpm-version: ${{ needs.verify-deployment-conditions.outputs.pnpm_version }}
          project-path: 'web'
      
      # テスト実行
      - name: Webアプリのテスト
        run: pnpm --filter @suzumina.click/web test

      - name: Next.jsアプリのビルド
        run: pnpm --filter @suzumina.click/web build
      
      # Google Cloud認証
      - name: Google Cloud認証の設定
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'cloud-run-deployer-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
      
      # gcloud CLIをセットアップ
      - name: gcloud CLIのセットアップ
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      # Dockerの認証設定
      - name: Dockerの認証設定
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
      
      # Artifact Registryリポジトリの確認
      - name: Artifact Registryリポジトリの確認
        run: |
          echo "Artifact Registryリポジトリを確認しています..."
          
          # リポジトリの存在確認のみ行う（Terraformで事前作成済みの前提）
          REPO_EXISTS=$(gcloud artifacts repositories list --location=${{ env.REGION }} --format="value(name)" | grep "^suzumina-click$" || echo "")
          
          if [ -z "$REPO_EXISTS" ]; then
            echo "::error::リポジトリが存在しません。Terraformで事前に作成してください。"
            echo "リポジトリ 'suzumina-click' が見つかりません。"
            exit 1
          else
            echo "リポジトリを確認しました: $REPO_EXISTS"
          fi
      
      # Dockerイメージのビルドとプッシュ
      - name: Dockerイメージのビルドとプッシュ
        id: docker-build
        run: |
          # イメージタグの設定（コミットハッシュとlatestを両方設定）
          GIT_SHA=$(git rev-parse --short HEAD)
          IMAGE_BASE="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/suzumina-click/nextjs-app"
          IMAGE_TAG="${IMAGE_BASE}:${GIT_SHA}"
          IMAGE_LATEST="${IMAGE_BASE}:latest"
          
          echo "イメージをビルドしています: ${IMAGE_TAG}"
          
          # gcloudの現在の認証情報を確認（デバッグ用）
          echo "認証情報の確認中..."
          gcloud auth list
          echo "認証済みサービスアカウント: $(gcloud auth list --filter=status:ACTIVE --format='value(account)')"
          
          # Secret Managerへのアクセス権限を確認（デバッグ用）
          echo "Secret Managerのアクセス権限を確認中..."
          gcloud projects get-iam-policy ${{ secrets.GCP_PROJECT_ID }} \
            --flatten="bindings[].members" \
            --format="table(bindings.role,bindings.members)" \
            --filter="bindings.members:cloud-run-deployer-sa AND bindings.role:secretmanager.secretAccessor"
          
          # Secret Managerからサービスアカウントキーを取得
          echo "Secret Managerからサービスアカウントキーを取得しています..."
          # デバッグ情報を追加（エラーの詳細出力）
          FIREBASE_SA_KEY_RESULT=$(gcloud secrets versions access latest \
            --secret="FIREBASE_SERVICE_ACCOUNT_KEY" \
            --project="${{ secrets.GCP_PROJECT_ID }}" 2>&1)
          
          # エラー処理を追加
          if [ $? -ne 0 ]; then
            echo "::error::Firebase Service Account Keyの取得に失敗しました"
            echo "エラー詳細: ${FIREBASE_SA_KEY_RESULT}"
            # シークレットの存在確認
            echo "シークレットの存在確認:"
            gcloud secrets list --filter="name:FIREBASE_SERVICE_ACCOUNT_KEY" --project="${{ secrets.GCP_PROJECT_ID }}"
            # バージョン確認
            echo "シークレットのバージョン確認:"
            gcloud secrets versions list FIREBASE_SERVICE_ACCOUNT_KEY --project="${{ secrets.GCP_PROJECT_ID }}"
            exit 1
          fi
          
          # 結果を変数に格納
          FIREBASE_SA_KEY="${FIREBASE_SA_KEY_RESULT}"
          
          # 取得したキーが有効なJSONかチェック
          if ! echo "${FIREBASE_SA_KEY}" | jq -e . >/dev/null 2>&1; then
            echo "::error::Firebase Service Account Keyが有効なJSON形式ではありません"
            echo "取得されたデータの先頭部分（安全のため一部のみ表示）: ${FIREBASE_SA_KEY:0:50}..."
            exit 1
          fi
          
          echo "Firebase Service Account Keyを取得しました"
          
          # ビルドとタグ付け
          # Dockerfileの場所を明示的に指定し、コンテキストをリポジトリのルートに設定
          # Firebase Admin SDK初期化に必要な環境変数を渡す
          docker build -f apps/web/Dockerfile \
            --build-arg FIREBASE_SERVICE_ACCOUNT_KEY="$FIREBASE_SA_KEY" \
            -t ${IMAGE_TAG} -t ${IMAGE_LATEST} .
          
          # イメージのプッシュ
          docker push ${IMAGE_TAG}
          docker push ${IMAGE_LATEST}
          
          echo "イメージがプッシュされました: ${IMAGE_TAG}"
          echo "image=${IMAGE_TAG}" >> $GITHUB_OUTPUT
      
      # Cloud Runへのデプロイ
      - name: Cloud Runへのデプロイ
        id: deploy-run
        run: |
          echo "Cloud Runサービスをデプロイしています..."
          
          # デプロイコマンド
          gcloud run deploy suzumina-click-nextjs-app \
            --image=${{ steps.docker-build.outputs.image }} \
            --platform=managed \
            --region=${{ env.REGION }} \
            --allow-unauthenticated \
            --quiet
          
          echo "デプロイが完了しました"
      
      # デプロイ後の確認
      - name: デプロイ結果の確認
        run: |
          # デプロイされたURLを取得して表示
          URL=$(gcloud run services describe suzumina-click-nextjs-app --platform=managed --region=${{ env.REGION }} --format="value(status.url)")
          echo "デプロイURL: $URL"
          echo "::notice title=Webアプリケーションデプロイ完了::$URL にデプロイされました"

  # Cloud Functionsのデプロイ
  deploy-cloud-functions:
    name: 'Cloud Functionsデプロイ'
    needs: [verify-deployment-conditions, deploy-web-app]
    # 変更検知で変更がある場合、または手動・CI経由の場合に実行
    if: |
      needs.verify-deployment-conditions.outputs.functions_changed == 'true' ||
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'workflow_run'
    runs-on: ubuntu-latest
    
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.verify-deployment-conditions.outputs.deploy_branch }}
      
      # 複合アクションを使用してNode.js環境をセットアップ
      - name: Node.js環境のセットアップ
        uses: ./.github/actions/setup-node-env
        with:
          node-version: ${{ needs.verify-deployment-conditions.outputs.node_version }}
          pnpm-version: ${{ needs.verify-deployment-conditions.outputs.pnpm_version }}
          project-path: 'functions'

      # テスト実行
      - name: Cloud Functionsのテスト
        run: pnpm --filter @suzumina.click/functions test
      
      - name: Cloud Functionsのビルド
        run: pnpm --filter @suzumina.click/functions build
      
      # Google Cloud認証
      - name: Google Cloud認証の設定
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'cloud-functions-deployer-sa@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com'
      
      # gcloud CLIをセットアップ
      - name: gcloud CLIのセットアップ
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      # pushイベント時は変更があったファイルだけをデプロイ
      - name: 変更された関数の検出（push時のみ）
        if: github.event_name == 'push'
        id: changed-functions
        run: |
          # 変更されたファイルからexportされている関数名を抽出
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep "^apps/functions/src/.*\.ts$" | grep -v "\.test\.ts$" || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "変更された関数ファイルはありません"
            echo "names=" >> $GITHUB_OUTPUT
            echo "has_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          FUNCTIONS=""
          for FILE in $CHANGED_FILES; do
            FUNCS=$(grep -o "export.*async function [a-zA-Z0-9_]\+" $FILE | sed -E 's/export.*function ([a-zA-Z0-9_]+).*/\1/' || true)
            if [ -n "$FUNCS" ]; then
              FUNCTIONS="$FUNCTIONS $FUNCS"
            fi
          done
          
          # 重複を削除して整形
          FUNCTIONS=$(echo "$FUNCTIONS" | tr ' ' '\n' | sort | uniq | tr '\n' ' ')
          echo "デプロイする関数: $FUNCTIONS"
          echo "names=$FUNCTIONS" >> $GITHUB_OUTPUT
          echo "has_changes=true" >> $GITHUB_OUTPUT

      # 手動/CI経由の場合は全関数を対象にする
      - name: すべての関数を取得（手動/CI経由の場合）
        if: github.event_name != 'push'
        id: all-functions
        run: |
          FUNCTIONS=$(grep -r "export.*async function" ./apps/functions/src --include="*.ts" | grep -v ".test.ts" | sed -E 's/.*export.*function ([a-zA-Z0-9_]+).*/\1/' | tr '\n' ' ')
          echo "デプロイする関数: $FUNCTIONS"
          echo "names=$FUNCTIONS" >> $GITHUB_OUTPUT

      # 関数デプロイ - push時の変更された関数のみ
      - name: 変更されたCloud Functionsのデプロイ（push時）
        if: github.event_name == 'push' && steps.changed-functions.outputs.has_changes == 'true'
        run: |
          # 関数名のリストをスペースで分割して処理
          FUNCTIONS="${{ steps.changed-functions.outputs.names }}"
          for FUNC in $FUNCTIONS; do
            echo "関数 $FUNC をデプロイしています..."
            
            # gcloudコマンドで関数をデプロイ
            gcloud functions deploy $FUNC \
              --gen2 \
              --region=${{ env.REGION }} \
              --runtime=nodejs20 \
              --source=./apps/functions \
              --entry-point=$FUNC
            
            if [ $? -eq 0 ]; then
              echo "関数 $FUNC のデプロイに成功しました"
            else
              echo "関数 $FUNC のデプロイに失敗しました"
              exit 1
            fi
          done

      # 関数デプロイ - 手動/CI経由の場合は全関数をデプロイ
      - name: すべてのCloud Functionsのデプロイ（手動/CI経由）
        if: github.event_name != 'push'
        run: |
          # 関数名のリストをスペースで分割して処理
          FUNCTIONS="${{ steps.all-functions.outputs.names }}"
          for FUNC in $FUNCTIONS; do
            echo "関数 $FUNC をデプロイしています..."
            
            # gcloudコマンドで関数をデプロイ
            gcloud functions deploy $FUNC \
              --gen2 \
              --region=${{ env.REGION }} \
              --runtime=nodejs20 \
              --source=./apps/functions \
              --entry-point=$FUNC
            
            if [ $? -eq 0 ]; then
              echo "関数 $FUNC のデプロイに成功しました"
            else
              echo "関数 $FUNC のデプロイに失敗しました"
              exit 1
            fi
          done
      
      # デプロイ情報の出力
      - name: デプロイサマリー（push時）
        if: github.event_name == 'push' && steps.changed-functions.outputs.has_changes == 'true'
        run: |
          FUNCTIONS="${{ steps.changed-functions.outputs.names }}"
          echo "デプロイ完了した関数:"
          for FUNC in $FUNCTIONS; do
            DETAILS=$(gcloud functions describe $FUNC --region=${{ env.REGION }} --gen2 --format="yaml(url)")
            URL=$(echo "$DETAILS" | grep "url:" | awk '{print $2}')
            echo "- $FUNC: $URL"
          done
          echo "::notice title=Cloud Functionsデプロイ完了::変更された関数がデプロイされました"

      # デプロイ情報の出力（手動/CI経由の場合）
      - name: デプロイサマリー（手動/CI経由）
        if: github.event_name != 'push'
        run: |
          FUNCTIONS="${{ steps.all-functions.outputs.names }}"
          echo "デプロイ完了した関数:"
          for FUNC in $FUNCTIONS; do
            DETAILS=$(gcloud functions describe $FUNC --region=${{ env.REGION }} --gen2 --format="yaml(url)")
            URL=$(echo "$DETAILS" | grep "url:" | awk '{print $2}')
            echo "- $FUNC: $URL"
          done
          echo "::notice title=Cloud Functionsデプロイ完了::すべての関数がデプロイされました"
      
      # 変更がなかった場合のメッセージ（push時のみ）
      - name: デプロイ不要メッセージ
        if: github.event_name == 'push' && steps.changed-functions.outputs.has_changes != 'true'
        run: |
          echo "::notice title=Cloud Functions変更なし::デプロイが必要な関数の変更はありませんでした"

  # デプロイ完了通知
  notify-deployment:
    name: 'デプロイ完了通知'
    needs: [verify-deployment-conditions, deploy-web-app, deploy-cloud-functions]
    # いずれかのデプロイが実行された場合に通知
    if: |
      always() &&
      (needs.deploy-web-app.result == 'success' || needs.deploy-cloud-functions.result == 'success')
    runs-on: ubuntu-latest
    
    steps:
      - name: デプロイ完了メッセージ
        run: |
          echo "::notice title=本番環境デプロイ完了::コンポーネントが正常にデプロイされました"
          echo "デプロイ日時: $(date '+%Y年%m月%d日 %H:%M:%S')"
          echo "トリガー: ${{ github.event_name }}"
          echo "実行者: ${{ github.actor }}"