name: Deploy Web App (Push to main)

on:
  push:
    branches: ["main"]
    paths:
      - "apps/web/**"
      - "packages/ui/**"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/reusable-deploy.yml"
      - "package.json"
      - "bun.lock"
      - "turbo.json"

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  ARTIFACT_REGISTRY_REPO: ${{ vars.ARTIFACT_REGISTRY_REPO }}

jobs:
  ci:
    name: Run CI Checks
    uses: ./.github/workflows/ci.yml

  deploy:
    name: Build and Deploy
    needs: [ci]
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      git_ref: ${{ github.ref }}
