name: Deploy Web App (Push to main)

on:
  push:
    branches: ["main"]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/reusable-deploy.yml" # Reusable workflow itself
      # Consider adding root config files if they affect the build
      # - "package.json"
      # - "bun.lock"
      # - "turbo.json"

# Environment variables needed by the reusable workflow
env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  ARTIFACT_REGISTRY_REPO: ${{ vars.ARTIFACT_REGISTRY_REPO }}
  CLOUD_RUN_SERVICE: "web"
  IMAGE_NAME: "web-app"

jobs:
  call-reusable-deploy:
    name: Build and Deploy
    # Use the reusable workflow from the same repository/commit
    # Do NOT specify @ref when calling a local reusable workflow
    uses: ./.github/workflows/reusable-deploy.yml
    # Pass required inputs
    with:
      git_ref: ${{ github.ref }} # Use the ref that triggered the workflow (main branch)
      image_tag: ${{ github.sha }} # Use the commit SHA as the image tag
    # Secrets can be passed if the reusable workflow defines them
    # secrets: inherit # Or pass specific secrets