name: Deploy Web App (Push to main)

on:
  push:
    branches: ["main"]
    paths:
      - "apps/web/**"
      - ".github/workflows/deploy.yml"
      - ".github/workflows/reusable-deploy.yml"
      - "package.json" # Trigger on root package changes
      - "bun.lock"     # Trigger on lock file changes
      - "turbo.json"   # Trigger on turbo config changes

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  ARTIFACT_REGISTRY_REPO: ${{ vars.ARTIFACT_REGISTRY_REPO }}

jobs:
  call-reusable-deploy:
    name: Build and Deploy
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      git_ref: ${{ github.ref }}
      image_tag: ${{ github.sha }}
    # secrets: inherit # If reusable workflow needs secrets