name: Manual Deploy Web App

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "開発環境へのデプロイを実行しますか？"
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  ARTIFACT_REGISTRY_REPO: ${{ vars.ARTIFACT_REGISTRY_REPO }}

jobs:
  call-reusable-deploy:
    name: Build and Deploy (Manual)
    if: ${{ inputs.confirm == true }}
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      # Use main branch ref for manual deploys
      git_ref: 'refs/heads/main'
      # Use the SHA associated with the workflow trigger event
      image_tag: ${{ github.sha }}
    # secrets: inherit # If reusable workflow needs secrets