name: Manual Deploy Web App

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: "開発環境へのデプロイを実行しますか？"
        required: true
        type: boolean
        default: false

# Environment variables needed by the reusable workflow
env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  ARTIFACT_REGISTRY_REPO: ${{ vars.ARTIFACT_REGISTRY_REPO }}
  CLOUD_RUN_SERVICE: "web"
  IMAGE_NAME: "web-app"

jobs:
  call-reusable-deploy:
    name: Build and Deploy (Manual)
    # Only run if the confirmation input is true
    if: ${{ inputs.confirm == true }}
    # Use the reusable workflow from the same repository/commit
    # Do NOT specify @ref when calling a local reusable workflow
    uses: ./.github/workflows/reusable-deploy.yml
    # Pass required inputs
    with:
      # For manual dispatch, use the ref of the main branch by default,
      # or allow specifying a ref via inputs if needed in the future.
      git_ref: 'refs/heads/main'
      # Use the SHA of the main branch head for the image tag
      image_tag: ${{ github.sha }} # Note: This SHA is from the workflow trigger event, not necessarily latest main. Consider fetching latest main SHA if needed.
    # Secrets can be passed if the reusable workflow defines them
    # secrets: inherit