# Reusable workflow for building and deploying to Firebase Hosting
name: Reusable Build and Deploy

on:
  workflow_call:
    inputs:
      channelId: # デプロイ先のチャンネルID (PRプレビューの場合は空、mainマージ時は 'live')
        required: false
        type: string
        default: '' # デフォルトは空文字 (PRプレビュー用)
    secrets:
      firebaseServiceAccount: # Firebase サービスアカウントキー
        required: true
      # --- フロントエンドビルドに必要な Secret を追加 ---
      NEXT_PUBLIC_FIREBASE_API_KEY:
        required: true
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
        required: true
      NEXT_PUBLIC_FIREBASE_PROJECT_ID:
        required: true
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:
        required: true
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
        required: true
      NEXT_PUBLIC_FIREBASE_APP_ID:
        required: true
      NEXT_PUBLIC_DISCORD_CLIENT_ID:
        required: true
      NEXT_PUBLIC_DISCORD_REDIRECT_URI:
        required: true
      NEXT_PUBLIC_FIREBASE_FUNCTIONS_AUTH_CALLBACK_URL:
        required: true
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID:
        required: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies and Build
        run: pnpm install --frozen-lockfile && pnpm build
        # --- ビルドステップに環境変数を渡す ---
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_DISCORD_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_DISCORD_CLIENT_ID }}
          NEXT_PUBLIC_DISCORD_REDIRECT_URI: ${{ secrets.NEXT_PUBLIC_DISCORD_REDIRECT_URI }}
          NEXT_PUBLIC_FIREBASE_FUNCTIONS_AUTH_CALLBACK_URL: ${{ secrets.NEXT_PUBLIC_FIREBASE_FUNCTIONS_AUTH_CALLBACK_URL }}
          NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.firebaseServiceAccount }}
          projectId: suzumina-click-firebase
          channelId: ${{ inputs.channelId }}
